// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: corelib/subscription/subscription.proto

package subscriptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscriptionAnchor — якорь начала, когда клиент называет его словом, а не
// позицией.
type SubscriptionAnchor int32

const (
	// Не назван. В ветви `SubscriptionRequest.start` отвергается
	// `INVALID_ARGUMENT`: выбрав ветвь якоря, вызывающий обязан назвать якорь.
	// Умолчание живёт у НЕЗАДАННОЙ ветви, а не у незаданного значения внутри
	// выбранной — иначе одно и то же намерение выражалось бы двумя способами.
	SubscriptionAnchor_SUBSCRIPTION_ANCHOR_UNSPECIFIED SubscriptionAnchor = 0
	// С начала журнала — всё, что владелец ещё удерживает.
	SubscriptionAnchor_BEGINNING SubscriptionAnchor = 1
	// С текущего конца — только то, что записано после открытия подписки.
	SubscriptionAnchor_CURRENT_END SubscriptionAnchor = 2
)

// Enum value maps for SubscriptionAnchor.
var (
	SubscriptionAnchor_name = map[int32]string{
		0: "SUBSCRIPTION_ANCHOR_UNSPECIFIED",
		1: "BEGINNING",
		2: "CURRENT_END",
	}
	SubscriptionAnchor_value = map[string]int32{
		"SUBSCRIPTION_ANCHOR_UNSPECIFIED": 0,
		"BEGINNING":                       1,
		"CURRENT_END":                     2,
	}
)

func (x SubscriptionAnchor) Enum() *SubscriptionAnchor {
	p := new(SubscriptionAnchor)
	*p = x
	return p
}

func (x SubscriptionAnchor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionAnchor) Descriptor() protoreflect.EnumDescriptor {
	return file_corelib_subscription_subscription_proto_enumTypes[0].Descriptor()
}

func (SubscriptionAnchor) Type() protoreflect.EnumType {
	return &file_corelib_subscription_subscription_proto_enumTypes[0]
}

func (x SubscriptionAnchor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionAnchor.Descriptor instead.
func (SubscriptionAnchor) EnumDescriptor() ([]byte, []int) {
	return file_corelib_subscription_subscription_proto_rawDescGZIP(), []int{0}
}

// Change — род изменения предмета.
type SubscriptionEvent_Change int32

const (
	// Не назван. Владелец обязан назвать род изменения: подписчик, ведущий своё
	// состояние, иначе не знает, добавить строку, обновить её или снять.
	SubscriptionEvent_CHANGE_UNSPECIFIED SubscriptionEvent_Change = 0
	SubscriptionEvent_CREATED            SubscriptionEvent_Change = 1
	SubscriptionEvent_UPDATED            SubscriptionEvent_Change = 2
	SubscriptionEvent_DELETED            SubscriptionEvent_Change = 3
)

// Enum value maps for SubscriptionEvent_Change.
var (
	SubscriptionEvent_Change_name = map[int32]string{
		0: "CHANGE_UNSPECIFIED",
		1: "CREATED",
		2: "UPDATED",
		3: "DELETED",
	}
	SubscriptionEvent_Change_value = map[string]int32{
		"CHANGE_UNSPECIFIED": 0,
		"CREATED":            1,
		"UPDATED":            2,
		"DELETED":            3,
	}
)

func (x SubscriptionEvent_Change) Enum() *SubscriptionEvent_Change {
	p := new(SubscriptionEvent_Change)
	*p = x
	return p
}

func (x SubscriptionEvent_Change) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionEvent_Change) Descriptor() protoreflect.EnumDescriptor {
	return file_corelib_subscription_subscription_proto_enumTypes[1].Descriptor()
}

func (SubscriptionEvent_Change) Type() protoreflect.EnumType {
	return &file_corelib_subscription_subscription_proto_enumTypes[1]
}

func (x SubscriptionEvent_Change) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionEvent_Change.Descriptor instead.
func (SubscriptionEvent_Change) EnumDescriptor() ([]byte, []int) {
	return file_corelib_subscription_subscription_proto_rawDescGZIP(), []int{2, 0}
}

// Reason — почему состояния нет. Словарь закрыт: «прочее» здесь не
// заводится, потому что корзина «прочее» перестаёт различать через месяц.
type SubscriptionEvent_StateUnavailable_Reason int32

const (
	// Не названа. Владелец обязан назвать причину; значение оставлено нулевым
	// ради совместимости разбора, а не как законный исход.
	SubscriptionEvent_StateUnavailable_REASON_UNSPECIFIED SubscriptionEvent_StateUnavailable_Reason = 0
	// Состояние не удалось сериализовать.
	SubscriptionEvent_StateUnavailable_NOT_SERIALIZABLE SubscriptionEvent_StateUnavailable_Reason = 1
	// Состояние на эту позицию владельцем больше не удерживается.
	SubscriptionEvent_StateUnavailable_NOT_RETAINED SubscriptionEvent_StateUnavailable_Reason = 2
	// Состояние есть, но вызывающему не показывается.
	SubscriptionEvent_StateUnavailable_WITHHELD SubscriptionEvent_StateUnavailable_Reason = 3
	// Состояние по этому предмету владельцем НЕ ПРОИЗВОДИТСЯ.
	//
	// Это СВОЙСТВО ЖУРНАЛА, а не сбой: собирать было нечего, попытки не было,
	// и повтор ничего не изменит. Тем оно и отличается от `NOT_SERIALIZABLE`,
	// где состояние есть, а собрать его не удалось: там разумное действие —
	// перечитать, здесь — сразу идти за предметом по `resource_id` (либо снять
	// его из своего состояния, если род изменения `DELETED`).
	//
	// Случая два, и оба живые: владелец, чей журнал не несёт состояния ни у
	// одного вида, и событие снятия — предмета больше нет, собирать нечего
	// by construction.
	//
	// Значение ДОБАВЛЕНО к закрытому словарю, а не заведено корзиной «прочее»:
	// до него владелец, у которого состояния не бывает, был вынужден называть
	// причиной соседнюю запись — то есть утверждать неудавшуюся попытку там,
	// где попытки не было. Подписчик, не знающий этого значения, читает его
	// как «состояния не будет» — ровно то, что означает ветвь.
	SubscriptionEvent_StateUnavailable_NOT_PRODUCED SubscriptionEvent_StateUnavailable_Reason = 4
)

// Enum value maps for SubscriptionEvent_StateUnavailable_Reason.
var (
	SubscriptionEvent_StateUnavailable_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "NOT_SERIALIZABLE",
		2: "NOT_RETAINED",
		3: "WITHHELD",
		4: "NOT_PRODUCED",
	}
	SubscriptionEvent_StateUnavailable_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED": 0,
		"NOT_SERIALIZABLE":   1,
		"NOT_RETAINED":       2,
		"WITHHELD":           3,
		"NOT_PRODUCED":       4,
	}
)

func (x SubscriptionEvent_StateUnavailable_Reason) Enum() *SubscriptionEvent_StateUnavailable_Reason {
	p := new(SubscriptionEvent_StateUnavailable_Reason)
	*p = x
	return p
}

func (x SubscriptionEvent_StateUnavailable_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionEvent_StateUnavailable_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_corelib_subscription_subscription_proto_enumTypes[2].Descriptor()
}

func (SubscriptionEvent_StateUnavailable_Reason) Type() protoreflect.EnumType {
	return &file_corelib_subscription_subscription_proto_enumTypes[2]
}

func (x SubscriptionEvent_StateUnavailable_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionEvent_StateUnavailable_Reason.Descriptor instead.
func (SubscriptionEvent_StateUnavailable_Reason) EnumDescriptor() ([]byte, []int) {
	return file_corelib_subscription_subscription_proto_rawDescGZIP(), []int{2, 0, 0}
}

// SubscriptionRequest — запрос подписки: чем сузить поток и с какого места его
// начать.
//
// # Оси фильтра: три, все необязательны, соединяются конъюнкцией
//
// Заданные оси сужают ВМЕСТЕ: событие приходит, только если удовлетворяет всем
// заданным сразу. Незаданная ось не сужает ничем — и это её ЕДИНСТВЕННОЕ
// значение: подписка без единой оси даёт то же, что подписка, где каждая ось
// перечислила все свои значения (в пределах прав вызывающего).
//
// У каждой оси проставлен ПРИЗНАК КАТЕГОРИИ — «якорная» либо «удобства», — и
// различие не косметическое. По якорной оси принимается решение о показе;
// исхода «ось названа, но не применена» у неё НЕ СУЩЕСТВУЕТ (см.
// `SubscriptionOpened.honored_filters`). По оси удобства доотбор на клиенте
// законен: он получит лишнее и отбросит.
//
// # Имени ресурса и меток здесь НЕТ, и вот почему
//
// ИМЯ — мутабельный косметический ярлык, а адресуется ресурс неизменяемым `id`.
// Подписка по имени МОЛЧА перестаёт совпадать после переименования: ни события,
// ни ошибки, ни следа — поток просто замолкает навсегда. Адресный отбор делает
// ось `ids`.
//
// МЕТКИ мутабельны, и ресурс входит в выборку и выходит из неё по их правке. Без
// предыдущего состояния выход из выборки неотличим от удаления ресурса, то есть
// подписчик принял бы правку метки за снос. Отбор по меткам делает КЛИЕНТ.
//
// ЦЕНА ЭТОГО РЕШЕНИЯ НАЗВАНА, а не подразумевается: клиент отбирает по меткам
// ровно там, где событие принесло состояние. Владелец, чей журнал состояния НЕ
// ПРОИЗВОДИТ, источника для такого отбора не даёт — по его видам отбор по меткам
// НЕИСПОЛНИМ, и подписчик, которому метки нужны, читает предмет по
// `resource_id`. Это не пропуск и не временное состояние: производит владелец
// состояние или нет, объявляется в потоке — причиной
// `SubscriptionEvent.StateUnavailable.NOT_PRODUCED`, отличимой машинно от сбоя
// сборки. Соврать здесь было бы дороже отказа: подписчик, поверивший обещанию,
// молча отобрал бы по меткам, которых не получал.
//
// Отсутствие этих полей — решение, а не пропуск. Поле без записанной причины
// отсутствия заводит следующий «для удобства», и он будет прав по-своему.
type SubscriptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kinds — виды предметов, о которых слать события. Категория: УДОБСТВА.
	//
	// Словарь видов принадлежит ВЛАДЕЛЬЦУ и им закрыт; фиксированного перечня
	// «ресурсы такого-то домена» здесь нет — иначе владелец, чьи события не про
	// ресурс, а про субъект прав, в эту форму не поместился бы вовсе.
	//
	// ГДЕ ЕГО ПРОЧИТАТЬ: `SubscriptionOpened.known_kinds` — служебное сообщение
	// открытия несёт словарь целиком и приходит первым. Подписка, не назвавшая ни
	// одного вида, законна и отказа не даёт, поэтому словарь читается ОДНИМ
	// открытием, а не перебором против отказа.
	//
	// # НАПИСАНИЕ ВИДА ОДНО НА ВСЁ ДЕРЕВО: это ТИП ОБЪЕКТА МОДЕЛИ ПРАВ
	//
	// Вид называется тем же словом, каким этот предмет зовёт модель прав
	// (`compute_instance`, `nlb_network_load_balancer`) — тем самым, что стоит в
	// `scope_extractor.object_type` контрактов домена. Слово НЕ придумывается
	// подпиской и не берётся из хранилища владельца: как строка журнала записана,
	// есть частное дело владельца, и наружу это не выходит.
	//
	// Причина ровно одна и она про клиента: словарь, у которого нет единственного
	// производителя, пишется столькими способами, сколько у него авторов, и
	// клиент, взявший написание у одного, не может знать, то ли оно. Здесь
	// производитель один — тот же, которым сервер решает вопрос о видимости
	// строки, — поэтому второго написания не существует by construction, а не по
	// договорённости.
	//
	// Форма слова: строчные латинские буквы, цифры и подчёркивание, первый знак —
	// буква. Владелец, объявивший вид иначе, НЕ ПОДНИМАЕТСЯ.
	//
	// Вид вне словаря владельца — `INVALID_ARGUMENT` с именем поля, названным
	// значением И перечнем известных видов, а НЕ открытый поток, в который никогда
	// ничего не придёт. Пустой поток есть утверждение «событий нет», которого
	// сервер не вправе делать про вход, которого он не понял; отказ, не называющий
	// годных значений, оставляет вызывающего ровно там, откуда он пришёл.
	Kinds []string `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// project_id — проект, к которому относятся события. Категория: ЯКОРНАЯ.
	//
	// По ней принимается решение о показе, поэтому владелец, не умеющий отобрать
	// по ней, ОТВЕРГАЕТ подписку, а не открывает её с оговоркой: «доотбор на
	// клиенте» означало бы, что границу доступа держит клиент.
	//
	// Незаданная ось проектом не сужает. Событие, не принадлежащее проекту вовсе
	// (предмет уровня аккаунта или кластера), выразимо — см.
	// `SubscriptionEvent.project_id`.
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// ids — неизменяемые идентификаторы предметов. Категория: УДОБСТВА.
	//
	// Это единственная ось, принимающая произвольную строку, и потому единственный
	// путь протащить мутабельную адресацию через иммутабельную. Имя ресурса,
	// поданное сюда, обязано быть отвергнуто `INVALID_ARGUMENT` — иначе подписка
	// откроется и замолчит навсегда, потому что имени не отвечает ни один
	// идентификатор.
	//
	// Идентификатор правильной формы, которому не отвечает ни один предмет, —
	// НЕ отказ: подписка открывается и просто не приносит по нему событий.
	// «Негодная форма» и «такого нет» — разные полосы, и подписка их не смешивает.
	Ids []string `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	// start — с какого места отдавать. Состояний ТРИ, и они различимы:
	// «с начала журнала», «с этой позиции», «с текущего конца».
	//
	// ИСХОД НЕЗАДАННОГО НАЗВАН, а не подразумевается: `start` не задан означает
	// ровно `CURRENT_END` — подписка на то, что произойдёт дальше. Выбор
	// осознанный: молчаливая полная выдача журнала («с начала») превращает
	// подписку в выгрузку и тем дороже, чем дольше журнал не чистили, а узнать об
	// этом вызывающий может только по счёту за неё.
	//
	// Types that are valid to be assigned to Start:
	//
	//	*SubscriptionRequest_Anchor
	//	*SubscriptionRequest_Position
	Start         isSubscriptionRequest_Start `protobuf_oneof:"start"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_corelib_subscription_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_subscription_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_corelib_subscription_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *SubscriptionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SubscriptionRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *SubscriptionRequest) GetStart() isSubscriptionRequest_Start {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SubscriptionRequest) GetAnchor() SubscriptionAnchor {
	if x != nil {
		if x, ok := x.Start.(*SubscriptionRequest_Anchor); ok {
			return x.Anchor
		}
	}
	return SubscriptionAnchor_SUBSCRIPTION_ANCHOR_UNSPECIFIED
}

func (x *SubscriptionRequest) GetPosition() string {
	if x != nil {
		if x, ok := x.Start.(*SubscriptionRequest_Position); ok {
			return x.Position
		}
	}
	return ""
}

type isSubscriptionRequest_Start interface {
	isSubscriptionRequest_Start()
}

type SubscriptionRequest_Anchor struct {
	// anchor — назвать место словом.
	Anchor SubscriptionAnchor `protobuf:"varint,10,opt,name=anchor,proto3,enum=corelib.subscription.SubscriptionAnchor,oneof"`
}

type SubscriptionRequest_Position struct {
	// position — НЕПРОЗРАЧНЫЙ ТОКЕН, выданный сервером, и ничего больше.
	//
	// Клиент хранит его и возвращает ДОСЛОВНО: не разбирает, не сравнивает два
	// токена между собой и не конструирует свой. Позиция, сконструированная или
	// изменённая клиентом, отвергается `INVALID_ARGUMENT` — а не принимается
	// «как похожая».
	//
	// ОБЯЗАТЕЛЬСТВО, РАДИ КОТОРОГО ПОЗИЦИЯ НЕПРОЗРАЧНА:
	//
	//	позиция, выданная сервером, обязана быть такой, что возобновление с неё
	//	не пропускает ни одной строки, закоммиченной ПОСЛЕ её выдачи.
	//
	// Оно записано здесь дословно, потому что непрозрачность его НЕ ОБЕСПЕЧИВАЕТ.
	// Непрозрачность покупает право починить внутреннюю форму позже, не ломая
	// контракт; она не чинит. Токен, кодирующий границу по МАКСИМУМУ ВИДИМОГО
	// номера, непрозрачен и всё равно теряет строку: номер присваивается на
	// вставке, видимость наступает на фиксации, поэтому писатель, закоммитивший
	// позже с меньшим номером, оказывается за границей — навсегда, молча и без
	// пропуска в нумерации, видимого клиенту. Скалярная граница законна;
	// граница по максимуму видимого — нет.
	//
	// Кодек позиции живёт там же, где объявлены прочие формы курсора этого
	// дерева, — в пакете `corelib/pagetoken`, и объявляется СВОИМ типом. Уже
	// объявленный там `Cursor` для неё НЕ ГОДИТСЯ: его семантика — «последняя
	// ОТДАННАЯ строка», а это дословно та граница, которую обязательство выше и
	// запрещает.
	//
	// Позиция принадлежит КЛИЕНТУ, а не подписке: сервер её не помнит и остаётся
	// stateless. Иначе возобновление привязывается к реплике, на которой
	// подписка была открыта, и переподключение к другой перестаёт работать.
	Position string `protobuf:"bytes,11,opt,name=position,proto3,oneof"`
}

func (*SubscriptionRequest_Anchor) isSubscriptionRequest_Start() {}

func (*SubscriptionRequest_Position) isSubscriptionRequest_Start() {}

// SubscriptionOpened — служебное сообщение, которое приходит ПЕРВЫМ и всегда.
//
// Оно приходит и тогда, когда событий нет вовсе: поток остаётся открытым, а
// клиент уже знает, с чего сервер начал и что именно он для него сделал. Только
// после него идут события.
//
// Тип, а не соглашение о порядке: соглашение нельзя ни импортировать, ни
// проверить, а всё, что сервер обязан сказать о принятой подписке, держится
// ровно на нём.
type SubscriptionOpened struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// position — позиция, с которой сервер начал отдавать. Непрозрачна ровно так
	// же, как `SubscriptionRequest.position`, и возвращается в неё дословно.
	Position string `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	// caught_up — исчерпан ли журнал на момент открытия.
	//
	// Этим «событий не было» отличается от «я подключился позже», и отличается ПО
	// СЛОВУ СЕРВЕРА, а не арифметикой клиента: над непрозрачным токеном сравнение
	// двух позиций невыразимо by construction, и непрозрачность именно этот ход и
	// запрещает.
	//
	// `true` + молчание = изменений не было. `false` + молчание = я ещё догоняю.
	CaughtUp bool `protobuf:"varint,2,opt,name=caught_up,json=caughtUp,proto3" json:"caught_up,omitempty"`
	// honored_filters — оси, которые этот владелец отобрал ЧЕСТНО.
	//
	// Значения — ИМЕНА ПОЛЕЙ `SubscriptionRequest`, как они объявлены в этом
	// контракте: `kinds`, `project_id`, `ids`. Имя поля контракта и есть провод,
	// поэтому свой второй словарь осей здесь не заводится — он разошёлся бы с
	// полями молча.
	//
	// Зачем перечень. Журналы владельцев устроены по-разному, и ось, выразимая
	// контрактом, не у каждого отбираема. Исходов у такой оси три: молча
	// проигнорировать — ЗАПРЕЩЕНО (вызывающий получит успех и решит, что его
	// параметр применён); отвергнуть — лишает подписки половину владельцев;
	// НАЗВАТЬ — то, что выбрано здесь. Цена названа: по неотобранной оси клиент
	// доотбирает сам.
	//
	// Исключение — ЯКОРНАЯ ось: её в этом перечне не бывает отсутствующей при
	// заданном значении, потому что владелец, не умеющий по ней отобрать,
	// подписку отвергает. Решение о показе не перекладывается на клиента.
	//
	// Владелец, отобравший все заданные оси, перечисляет их все, и перечень
	// совпадает с заданными вызывающим.
	HonoredFilters []string `protobuf:"bytes,3,rep,name=honored_filters,json=honoredFilters,proto3" json:"honored_filters,omitempty"`
	// earliest_resumable_position — самая ранняя позиция, с которой возобновление
	// ещё возможно.
	//
	// Владелец, переставший удерживать часть журнала, обязан уметь сказать
	// «твоя позиция больше не возобновима» ЯВНО и назвать место, с которого
	// подписка возможна, — а не начать молча с ближайшего удержанного. Молчаливое
	// начало клиент запишет как «изменений не было», и дописать этот исход потом
	// будет ломающим изменением.
	//
	// Отказ на невозобновимой позиции называет ЭТУ ЖЕ величину, поэтому она
	// объявлена одним полем, а не двумя похожими в двух местах.
	EarliestResumablePosition string `protobuf:"bytes,4,opt,name=earliest_resumable_position,json=earliestResumablePosition,proto3" json:"earliest_resumable_position,omitempty"`
	// retains_everything — владелец удерживает журнал целиком.
	//
	// Тогда отказ «позиция утрачена» не наступает никогда, и это СВОЙСТВО
	// ВЛАДЕЛЬЦА, объявленное им, а не умолчание формы: при `true` поле
	// `earliest_resumable_position` не несёт горизонта, потому что горизонта нет.
	RetainsEverything bool `protobuf:"varint,5,opt,name=retains_everything,json=retainsEverything,proto3" json:"retains_everything,omitempty"`
	// known_kinds — ЗАКРЫТЫЙ СЛОВАРЬ ВИДОВ этого владельца, целиком.
	//
	// Это ответ на вопрос «что вообще можно назвать в `SubscriptionRequest.kinds`».
	// До него ответа не было НИ ОДНОГО: словарь принадлежит владельцу, объявлен
	// закрытым, а прочесть его было неоткуда — оставался перебор против отказа на
	// живой ручке. Перебор не воспроизводится при добавлении домена: новый
	// владелец заводит свои виды, и узнать о них снова стало бы неоткуда.
	//
	// # ПОЧЕМУ ЗДЕСЬ, А НЕ ПЕРЕЧИСЛЕНИЕМ В КОНТРАКТЕ И НЕ ОТДЕЛЬНЫМ ГЛАГОЛОМ
	//
	// Перечислением НЕЛЬЗЯ: словарь принадлежит владельцу, а эта форма — общая.
	// Перечисление в ней означало бы, что виды всех владельцев объявлены здесь, и
	// тогда владелец, чьи события не про ресурс, а про субъект прав, в форму не
	// поместился бы вовсе — ровно то, что оговорено у поля `kinds`. Плюс каждый
	// новый вид становился бы правкой ОБЩЕГО контракта, то есть словарь пополнялся
	// бы правкой документа, а не по построению.
	//
	// Отдельным глаголом МОЖНО, и цена измерена, а не предположена: глагол — это
	// вторая запись каталога прав (обе встроенные копии обязаны остаться
	// байт-идентичными), регистрация у КАЖДОГО владельца, второй путь на крае и
	// второе место, где словарь может разойтись с тем, чем сервер на самом деле
	// судит. Здесь же он не может разойтись by construction: сервер отдаёт ровно
	// тот перечень, которым отвергает неизвестный вид.
	//
	// Служебное сообщение приходит ПЕРВЫМ и ВСЕГДА и уже везётся по проводу — то
	// есть поверхность не расширяется вовсе, а до браузера словарь доезжает через
	// существующую проекцию края без единой её правки.
	//
	// # КАК ЕГО ПРОЧИТАТЬ, НЕ ЗНАЯ НИ ОДНОГО ВИДА
	//
	// Открыть подписку, НЕ называя `kinds`: незаданная ось не сужает, отказа не
	// будет, а первое же сообщение принесёт словарь целиком. Названный неизвестный
	// вид отвергается ДО открытия — поэтому узнать словарь отказом нельзя, и
	// отказ по этой причине называет его сам.
	//
	// # ПОРЯДОК ЗНАЧИМ: перечень отсортирован
	//
	// Он приходит в возрастающем лексикографическом порядке, и это ЧАСТЬ
	// КОНТРАКТА, а не «как получилось»: словарь живёт отображением, обход
	// отображения в Go случаен by construction, и клиент, ведущий своё состояние
	// по индексу, читал бы каждое открытие как смену словаря.
	//
	// # ЧТО ЭТО НЕ ЗНАЧИТ
	//
	// Не значит «по каждому из них тебе придут события»: словарь есть объявление
	// ВЛАДЕЛЬЦА, а не выборка по правам вызывающего. Показ решается построчно, и
	// вид, на который у вызывающего нет прав, остаётся в словаре — иначе перечень
	// стал бы способом узнать, что кому доступно.
	//
	// Пустым не бывает: владелец с пустым словарём не поднимается вовсе — поток,
	// из которого не доставляется ничего, объявлением подписки не является.
	KnownKinds    []string `protobuf:"bytes,6,rep,name=known_kinds,json=knownKinds,proto3" json:"known_kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionOpened) Reset() {
	*x = SubscriptionOpened{}
	mi := &file_corelib_subscription_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionOpened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionOpened) ProtoMessage() {}

func (x *SubscriptionOpened) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_subscription_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionOpened.ProtoReflect.Descriptor instead.
func (*SubscriptionOpened) Descriptor() ([]byte, []int) {
	return file_corelib_subscription_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriptionOpened) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *SubscriptionOpened) GetCaughtUp() bool {
	if x != nil {
		return x.CaughtUp
	}
	return false
}

func (x *SubscriptionOpened) GetHonoredFilters() []string {
	if x != nil {
		return x.HonoredFilters
	}
	return nil
}

func (x *SubscriptionOpened) GetEarliestResumablePosition() string {
	if x != nil {
		return x.EarliestResumablePosition
	}
	return ""
}

func (x *SubscriptionOpened) GetRetainsEverything() bool {
	if x != nil {
		return x.RetainsEverything
	}
	return false
}

func (x *SubscriptionOpened) GetKnownKinds() []string {
	if x != nil {
		return x.KnownKinds
	}
	return nil
}

// SubscriptionEvent — оболочка события: то, что приходит в потоке после
// `SubscriptionOpened`.
//
// # Что в оболочке, а что в нагрузке
//
// В оболочке лежит всё, по чему сервер принимает решения и по чему клиент ведёт
// своё состояние: позиция, вид, идентификатор, ЯКОРЬ АВТОРИЗАЦИИ и род
// изменения. В нагрузке — состояние предмета, специфичное для владельца.
//
// # Причины остановки потока здесь НЕТ, и это намеренно
//
// Ничто в этой форме не обязывает сервер сообщать исход остановки полезной
// нагрузкой: закрытие потока (в том числе по отозванному доступу) остаётся
// статусом вызова, который следующая фаза вправе выбрать отличимым. Обязательное
// поле «причина остановки» внутри события загнало бы этот исход в контракт
// данных.
type SubscriptionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// position — позиция ЭТОГО события. Непрозрачна; клиент запоминает её и
	// возвращает дословно, чтобы возобновиться отсюда.
	Position string `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	// kind — вид предмета из закрытого словаря ВЛАДЕЛЬЦА, в том же написании, в
	// каком его принимает ось `SubscriptionRequest.kinds` и в каком его
	// перечисляет `SubscriptionOpened.known_kinds`.
	//
	// Написание одно на всё дерево — тип объекта модели прав; чем оно держится и
	// почему выбрано именно оно, сказано у поля `kinds`. Слово, которым владелец
	// записал строку в своём журнале, сюда не попадает: оно частное.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// resource_id — неизменяемый идентификатор предмета. По нему сужает ось
	// `SubscriptionRequest.ids`.
	//
	// Может быть пуст: не всякое событие относится к ресурсу (предметом бывает
	// субъект прав), и непустой идентификатор ресурса не является условием ни
	// открытия подписки, ни доставки события.
	ResourceId string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// project_id — АВТОРИЗУЕМЫЙ ЯКОРЬ, и он стоит полем ОБОЛОЧКИ, а не внутри
	// нагрузки.
	//
	// Решение «кому это показать» принимается по нему БЕЗ обращения к предмету.
	// Для события удаления это несущее: обратиться не к чему — предмета больше
	// нет, а нагрузка у удаления беднее всего. Якорь внутри нагрузки означал бы
	// выбор из двух негодных: спрашивать модель прав про несуществующий объект
	// либо не показывать удаления вовсе. Второе наступает ТИХО, и цена его — та
	// самая, ради которой заводится подписка: потребитель, снявший поллинг,
	// никогда не узнает об удалении и будет держать удалённые строки вечно.
	//
	// Пусто означает «событие не принадлежит проекту» — предмет уровня аккаунта
	// или кластера. Это законное состояние, а не пропуск.
	ProjectId string `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// change — род изменения. Словарь платформенный, в отличие от `kind`: действие
	// потребителя зависит именно от него, и различать снос от правки обязан уметь
	// всякий подписчик, не зная домена.
	Change SubscriptionEvent_Change `protobuf:"varint,5,opt,name=change,proto3,enum=corelib.subscription.SubscriptionEvent_Change" json:"change,omitempty"`
	// Носитель нагрузки — ВЫБОР ИЗ ДВУХ ВЕТВЕЙ: состояние ЛИБО признак, что
	// состояния нет.
	//
	// Ветвление объявляет две альтернативы, но само по себе не требует выбрать
	// ветвь или заполнить `state`. Пустая нагрузка НИКОГДА не означает «у предмета
	// не осталось полей»: недоступность состояния передаётся отдельной ветвью
	// `state_unavailable`, а не пустым объектом вместо неё.
	//
	// Подписчик, получивший непустую нагрузку, вправе читать её как ПОЛНОЕ
	// состояние предмета — и это единственный случай, когда он вправе так делать.
	//
	// Types that are valid to be assigned to Carrier:
	//
	//	*SubscriptionEvent_State
	//	*SubscriptionEvent_StateUnavailable_
	Carrier       isSubscriptionEvent_Carrier `protobuf_oneof:"carrier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionEvent) Reset() {
	*x = SubscriptionEvent{}
	mi := &file_corelib_subscription_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionEvent) ProtoMessage() {}

func (x *SubscriptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_subscription_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionEvent) Descriptor() ([]byte, []int) {
	return file_corelib_subscription_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionEvent) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *SubscriptionEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SubscriptionEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *SubscriptionEvent) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SubscriptionEvent) GetChange() SubscriptionEvent_Change {
	if x != nil {
		return x.Change
	}
	return SubscriptionEvent_CHANGE_UNSPECIFIED
}

func (x *SubscriptionEvent) GetCarrier() isSubscriptionEvent_Carrier {
	if x != nil {
		return x.Carrier
	}
	return nil
}

func (x *SubscriptionEvent) GetState() *anypb.Any {
	if x != nil {
		if x, ok := x.Carrier.(*SubscriptionEvent_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *SubscriptionEvent) GetStateUnavailable() *SubscriptionEvent_StateUnavailable {
	if x != nil {
		if x, ok := x.Carrier.(*SubscriptionEvent_StateUnavailable_); ok {
			return x.StateUnavailable
		}
	}
	return nil
}

type isSubscriptionEvent_Carrier interface {
	isSubscriptionEvent_Carrier()
}

type SubscriptionEvent_State struct {
	// state — состояние предмета. Тип НАЗВАН: `Any` несёт имя типа на проводе,
	// и ключи нагрузки суть поля этого типа, объявленные контрактом владельца.
	//
	// Свободной структуры здесь нет намеренно. У неё ключи на проводе
	// производятся от имён идентификаторов Go, `buf breaking` этого не видит
	// by construction (в контракте написано «объект»), и обычный внутренний
	// рефактор молча ломает публичную нагрузку.
	State *anypb.Any `protobuf:"bytes,10,opt,name=state,proto3,oneof"`
}

type SubscriptionEvent_StateUnavailable_ struct {
	// state_unavailable — состояния по этому событию не будет, и сказано почему.
	StateUnavailable *SubscriptionEvent_StateUnavailable `protobuf:"bytes,11,opt,name=state_unavailable,json=stateUnavailable,proto3,oneof"`
}

func (*SubscriptionEvent_State) isSubscriptionEvent_Carrier() {}

func (*SubscriptionEvent_StateUnavailable_) isSubscriptionEvent_Carrier() {}

// StateUnavailable — вторая ветвь носителя: состояние предмета недоступно.
//
// Это НЕ причина остановки потока и не отказ вызова: поток продолжается, а
// подписчик узнаёт, что по этому конкретному событию состояния не будет.
type SubscriptionEvent_StateUnavailable struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Reason        SubscriptionEvent_StateUnavailable_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=corelib.subscription.SubscriptionEvent_StateUnavailable_Reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionEvent_StateUnavailable) Reset() {
	*x = SubscriptionEvent_StateUnavailable{}
	mi := &file_corelib_subscription_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionEvent_StateUnavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionEvent_StateUnavailable) ProtoMessage() {}

func (x *SubscriptionEvent_StateUnavailable) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_subscription_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionEvent_StateUnavailable.ProtoReflect.Descriptor instead.
func (*SubscriptionEvent_StateUnavailable) Descriptor() ([]byte, []int) {
	return file_corelib_subscription_subscription_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SubscriptionEvent_StateUnavailable) GetReason() SubscriptionEvent_StateUnavailable_Reason {
	if x != nil {
		return x.Reason
	}
	return SubscriptionEvent_StateUnavailable_REASON_UNSPECIFIED
}

var File_corelib_subscription_subscription_proto protoreflect.FileDescriptor

const file_corelib_subscription_subscription_proto_rawDesc = "" +
	"\n" +
	"'corelib/subscription/subscription.proto\x12\x14corelib.subscription\x1a\x19google/protobuf/any.proto\"\xc7\x01\n" +
	"\x13SubscriptionRequest\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\x12B\n" +
	"\x06anchor\x18\n" +
	" \x01(\x0e2(.corelib.subscription.SubscriptionAnchorH\x00R\x06anchor\x12\x1c\n" +
	"\bposition\x18\v \x01(\tH\x00R\bpositionB\a\n" +
	"\x05start\"\x86\x02\n" +
	"\x12SubscriptionOpened\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\tR\bposition\x12\x1b\n" +
	"\tcaught_up\x18\x02 \x01(\bR\bcaughtUp\x12'\n" +
	"\x0fhonored_filters\x18\x03 \x03(\tR\x0ehonoredFilters\x12>\n" +
	"\x1bearliest_resumable_position\x18\x04 \x01(\tR\x19earliestResumablePosition\x12-\n" +
	"\x12retains_everything\x18\x05 \x01(\bR\x11retainsEverything\x12\x1f\n" +
	"\vknown_kinds\x18\x06 \x03(\tR\n" +
	"knownKinds\"\x8e\x05\n" +
	"\x11SubscriptionEvent\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\tR\bposition\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12F\n" +
	"\x06change\x18\x05 \x01(\x0e2..corelib.subscription.SubscriptionEvent.ChangeR\x06change\x12,\n" +
	"\x05state\x18\n" +
	" \x01(\v2\x14.google.protobuf.AnyH\x00R\x05state\x12g\n" +
	"\x11state_unavailable\x18\v \x01(\v28.corelib.subscription.SubscriptionEvent.StateUnavailableH\x00R\x10stateUnavailable\x1a\xd5\x01\n" +
	"\x10StateUnavailable\x12W\n" +
	"\x06reason\x18\x01 \x01(\x0e2?.corelib.subscription.SubscriptionEvent.StateUnavailable.ReasonR\x06reason\"h\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NOT_SERIALIZABLE\x10\x01\x12\x10\n" +
	"\fNOT_RETAINED\x10\x02\x12\f\n" +
	"\bWITHHELD\x10\x03\x12\x10\n" +
	"\fNOT_PRODUCED\x10\x04\"G\n" +
	"\x06Change\x12\x16\n" +
	"\x12CHANGE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\v\n" +
	"\aUPDATED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03B\t\n" +
	"\acarrier*Y\n" +
	"\x12SubscriptionAnchor\x12#\n" +
	"\x1fSUBSCRIPTION_ANCHOR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tBEGINNING\x10\x01\x12\x0f\n" +
	"\vCURRENT_END\x10\x02BIZGgithub.com/PRO-Robotech/corelib/api/corelib/subscription;subscriptionv1b\x06proto3"

var (
	file_corelib_subscription_subscription_proto_rawDescOnce sync.Once
	file_corelib_subscription_subscription_proto_rawDescData []byte
)

func file_corelib_subscription_subscription_proto_rawDescGZIP() []byte {
	file_corelib_subscription_subscription_proto_rawDescOnce.Do(func() {
		file_corelib_subscription_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corelib_subscription_subscription_proto_rawDesc), len(file_corelib_subscription_subscription_proto_rawDesc)))
	})
	return file_corelib_subscription_subscription_proto_rawDescData
}

var file_corelib_subscription_subscription_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_corelib_subscription_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_corelib_subscription_subscription_proto_goTypes = []any{
	(SubscriptionAnchor)(0),                        // 0: corelib.subscription.SubscriptionAnchor
	(SubscriptionEvent_Change)(0),                  // 1: corelib.subscription.SubscriptionEvent.Change
	(SubscriptionEvent_StateUnavailable_Reason)(0), // 2: corelib.subscription.SubscriptionEvent.StateUnavailable.Reason
	(*SubscriptionRequest)(nil),                    // 3: corelib.subscription.SubscriptionRequest
	(*SubscriptionOpened)(nil),                     // 4: corelib.subscription.SubscriptionOpened
	(*SubscriptionEvent)(nil),                      // 5: corelib.subscription.SubscriptionEvent
	(*SubscriptionEvent_StateUnavailable)(nil),     // 6: corelib.subscription.SubscriptionEvent.StateUnavailable
	(*anypb.Any)(nil),                              // 7: google.protobuf.Any
}
var file_corelib_subscription_subscription_proto_depIdxs = []int32{
	0, // 0: corelib.subscription.SubscriptionRequest.anchor:type_name -> corelib.subscription.SubscriptionAnchor
	1, // 1: corelib.subscription.SubscriptionEvent.change:type_name -> corelib.subscription.SubscriptionEvent.Change
	7, // 2: corelib.subscription.SubscriptionEvent.state:type_name -> google.protobuf.Any
	6, // 3: corelib.subscription.SubscriptionEvent.state_unavailable:type_name -> corelib.subscription.SubscriptionEvent.StateUnavailable
	2, // 4: corelib.subscription.SubscriptionEvent.StateUnavailable.reason:type_name -> corelib.subscription.SubscriptionEvent.StateUnavailable.Reason
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_corelib_subscription_subscription_proto_init() }
func file_corelib_subscription_subscription_proto_init() {
	if File_corelib_subscription_subscription_proto != nil {
		return
	}
	file_corelib_subscription_subscription_proto_msgTypes[0].OneofWrappers = []any{
		(*SubscriptionRequest_Anchor)(nil),
		(*SubscriptionRequest_Position)(nil),
	}
	file_corelib_subscription_subscription_proto_msgTypes[2].OneofWrappers = []any{
		(*SubscriptionEvent_State)(nil),
		(*SubscriptionEvent_StateUnavailable_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corelib_subscription_subscription_proto_rawDesc), len(file_corelib_subscription_subscription_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_corelib_subscription_subscription_proto_goTypes,
		DependencyIndexes: file_corelib_subscription_subscription_proto_depIdxs,
		EnumInfos:         file_corelib_subscription_subscription_proto_enumTypes,
		MessageInfos:      file_corelib_subscription_subscription_proto_msgTypes,
	}.Build()
	File_corelib_subscription_subscription_proto = out.File
	file_corelib_subscription_subscription_proto_goTypes = nil
	file_corelib_subscription_subscription_proto_depIdxs = nil
}
