// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: corelib/subscription/subscription_service.proto

package subscriptionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalSubscriptionService_Subscribe_FullMethodName = "/corelib.subscription.InternalSubscriptionService/Subscribe"
)

// InternalSubscriptionServiceClient is the client API for InternalSubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalSubscriptionService — ЕДИНСТВЕННЫЙ глагол подписки на платформе.
//
// # Почему имя начинается с `Internal`
//
// Это не украшение: префикс имени службы есть ДЕЙСТВУЮЩИЙ дискриминатор запрета
// #6 на всей популяции методов дерева (`gateway/internal/allowlist`
// `HasInternalSuffix`). Метод с таким именем не попадает во внешний
// маршрутизатор by construction, и проверка этого — не обещание, а обход
// дескрипторов.
//
// Подписку открывает наш же модуль по проверенному сертификату. Проекция потока
// в браузер (kacho#1020) идёт ЧЕРЕЗ КРАЙ, который сам становится потребителем
// этого метода, — а не публикацией метода наружу.
//
// # Где этот глагол доступен КЛИЕНТУ
//
// Недостижимым он не является, и сказать это здесь обязательно: читатель одного
// контракта видит слово `Internal` и заключает «не для меня» — заключение
// неверное, и стоило оно имитации клиента трёх часов.
//
// Клиент открывает поток у КРАЯ: `GET /subscription/v1/events` (Server-Sent
// Events), где владелец журнала называется параметром `owner`, а оси фильтра —
// параметрами `kinds`, `projectId`, `ids` и `start`. Позиция возвращается
// заголовком `Last-Event-ID`. Адрес, словари и кадры описаны страницей
// «Подписка на изменения» документации края; здесь они не воспроизводятся,
// чтобы не завести второго места об одном предмете.
//
// # Один сервис на всех владельцев, а не по сервису на домен
//
// Полное имя метода одно (`/corelib.subscription.InternalSubscriptionService/Subscribe`),
// и каждый владелец журнала регистрирует ЭТОТ сервис на своём внутреннем
// слушателе. Имена gRPC-сервисов уникальны в пределах процесса, а процессы у
// владельцев разные — поэтому одно объявление обслуживает всех, и запись каталога
// прав тоже одна.
//
// Доменного объявления рядом не заводится, и это держит гейт дерева
// (`internal/repohygiene/subscriptionformsingularity.go`), а не эта фраза.
//
// # Только внутренний слушатель
//
// Внешнего пути у метода нет: `google.api.http` не объявлен, а имя службы
// выводит её из внешнего маршрутизатора механически (см. выше).
type InternalSubscriptionServiceClient interface {
	// Subscribe — открыть поток изменений журнала владельца.
	//
	// # Решение о показе принимается НА КАЖДОЙ ОТДАВАЕМОЙ СТРОКЕ
	//
	// Единого объекта, о котором можно было бы задать ОДИН вопрос при открытии, у
	// этого метода не существует: поток несёт события разных предметов разных
	// проектов, и какие именно — заранее не известно. Поэтому метод объявлен
	// `scope_filtered`: край пообъектного вопроса не задаёт, а владелец сужает
	// поток по правам вызывающего на каждой строке, партиями, тем же сужателем,
	// что и списки.
	//
	// Следствие, названное прямо: у метода НЕТ полосы, на которую можно было бы
	// откатиться при неработающем сужателе. Сервер отказывает в открытии потока,
	// если сужатель отсутствует либо не сужает, а боевая стража отказывает в
	// старте процессу, объявившему `scope_filtered` без работающего фильтра.
	//
	// # Что этот метод НЕ делает
	//
	// Он не заменяет полл операции: событие пишется в той же транзакции, что и
	// ресурсная строка, поэтому при отказе операции события нет ВОВСЕ, и
	// наблюдатель ресурсов не отличит «ещё делается» от «упало».
	Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionMessage], error)
}

type internalSubscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalSubscriptionServiceClient(cc grpc.ClientConnInterface) InternalSubscriptionServiceClient {
	return &internalSubscriptionServiceClient{cc}
}

func (c *internalSubscriptionServiceClient) Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InternalSubscriptionService_ServiceDesc.Streams[0], InternalSubscriptionService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscriptionRequest, SubscriptionMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalSubscriptionService_SubscribeClient = grpc.ServerStreamingClient[SubscriptionMessage]

// InternalSubscriptionServiceServer is the server API for InternalSubscriptionService service.
// All implementations must embed UnimplementedInternalSubscriptionServiceServer
// for forward compatibility.
//
// InternalSubscriptionService — ЕДИНСТВЕННЫЙ глагол подписки на платформе.
//
// # Почему имя начинается с `Internal`
//
// Это не украшение: префикс имени службы есть ДЕЙСТВУЮЩИЙ дискриминатор запрета
// #6 на всей популяции методов дерева (`gateway/internal/allowlist`
// `HasInternalSuffix`). Метод с таким именем не попадает во внешний
// маршрутизатор by construction, и проверка этого — не обещание, а обход
// дескрипторов.
//
// Подписку открывает наш же модуль по проверенному сертификату. Проекция потока
// в браузер (kacho#1020) идёт ЧЕРЕЗ КРАЙ, который сам становится потребителем
// этого метода, — а не публикацией метода наружу.
//
// # Где этот глагол доступен КЛИЕНТУ
//
// Недостижимым он не является, и сказать это здесь обязательно: читатель одного
// контракта видит слово `Internal` и заключает «не для меня» — заключение
// неверное, и стоило оно имитации клиента трёх часов.
//
// Клиент открывает поток у КРАЯ: `GET /subscription/v1/events` (Server-Sent
// Events), где владелец журнала называется параметром `owner`, а оси фильтра —
// параметрами `kinds`, `projectId`, `ids` и `start`. Позиция возвращается
// заголовком `Last-Event-ID`. Адрес, словари и кадры описаны страницей
// «Подписка на изменения» документации края; здесь они не воспроизводятся,
// чтобы не завести второго места об одном предмете.
//
// # Один сервис на всех владельцев, а не по сервису на домен
//
// Полное имя метода одно (`/corelib.subscription.InternalSubscriptionService/Subscribe`),
// и каждый владелец журнала регистрирует ЭТОТ сервис на своём внутреннем
// слушателе. Имена gRPC-сервисов уникальны в пределах процесса, а процессы у
// владельцев разные — поэтому одно объявление обслуживает всех, и запись каталога
// прав тоже одна.
//
// Доменного объявления рядом не заводится, и это держит гейт дерева
// (`internal/repohygiene/subscriptionformsingularity.go`), а не эта фраза.
//
// # Только внутренний слушатель
//
// Внешнего пути у метода нет: `google.api.http` не объявлен, а имя службы
// выводит её из внешнего маршрутизатора механически (см. выше).
type InternalSubscriptionServiceServer interface {
	// Subscribe — открыть поток изменений журнала владельца.
	//
	// # Решение о показе принимается НА КАЖДОЙ ОТДАВАЕМОЙ СТРОКЕ
	//
	// Единого объекта, о котором можно было бы задать ОДИН вопрос при открытии, у
	// этого метода не существует: поток несёт события разных предметов разных
	// проектов, и какие именно — заранее не известно. Поэтому метод объявлен
	// `scope_filtered`: край пообъектного вопроса не задаёт, а владелец сужает
	// поток по правам вызывающего на каждой строке, партиями, тем же сужателем,
	// что и списки.
	//
	// Следствие, названное прямо: у метода НЕТ полосы, на которую можно было бы
	// откатиться при неработающем сужателе. Сервер отказывает в открытии потока,
	// если сужатель отсутствует либо не сужает, а боевая стража отказывает в
	// старте процессу, объявившему `scope_filtered` без работающего фильтра.
	//
	// # Что этот метод НЕ делает
	//
	// Он не заменяет полл операции: событие пишется в той же транзакции, что и
	// ресурсная строка, поэтому при отказе операции события нет ВОВСЕ, и
	// наблюдатель ресурсов не отличит «ещё делается» от «упало».
	Subscribe(*SubscriptionRequest, grpc.ServerStreamingServer[SubscriptionMessage]) error
	mustEmbedUnimplementedInternalSubscriptionServiceServer()
}

// UnimplementedInternalSubscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalSubscriptionServiceServer struct{}

func (UnimplementedInternalSubscriptionServiceServer) Subscribe(*SubscriptionRequest, grpc.ServerStreamingServer[SubscriptionMessage]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedInternalSubscriptionServiceServer) mustEmbedUnimplementedInternalSubscriptionServiceServer() {
}
func (UnimplementedInternalSubscriptionServiceServer) testEmbeddedByValue() {}

// UnsafeInternalSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalSubscriptionServiceServer will
// result in compilation errors.
type UnsafeInternalSubscriptionServiceServer interface {
	mustEmbedUnimplementedInternalSubscriptionServiceServer()
}

func RegisterInternalSubscriptionServiceServer(s grpc.ServiceRegistrar, srv InternalSubscriptionServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalSubscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalSubscriptionService_ServiceDesc, srv)
}

func _InternalSubscriptionService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalSubscriptionServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscriptionRequest, SubscriptionMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalSubscriptionService_SubscribeServer = grpc.ServerStreamingServer[SubscriptionMessage]

// InternalSubscriptionService_ServiceDesc is the grpc.ServiceDesc for InternalSubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalSubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "corelib.subscription.InternalSubscriptionService",
	HandlerType: (*InternalSubscriptionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _InternalSubscriptionService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "corelib/subscription/subscription_service.proto",
}
