// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: corelib/subscription/subscription_service.proto

package subscriptionv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Глагол подписки платформы и носитель его потока.
//
// # Почему ОТДЕЛЬНЫЙ файл от формы
//
// Форма (`subscription.proto`) обязана импортироваться кем угодно и потому не
// зависит ни от одного контракта дерева. Глагол несёт аннотации каталога прав —
// зависимость от контракта другого домена, — и, лежи он рядом с формой, форма
// перестала бы быть общей.
//
// Разделение не косметическое: домены импортируют ФОРМУ (чтобы говорить на одном
// языке подписки) и НЕ обязаны импортировать глагол — его регистрирует общий
// сервер `corelib/subscription`, один на платформу.
// SubscriptionMessage — то, что едет по потоку: ЛИБО служебное сообщение
// открытия, ЛИБО событие.
//
// # Зачем носитель, а не «поток событий, а служебное — заголовком»
//
// `SubscriptionOpened` обязано прийти ПЕРВЫМ и ВСЕГДА, в том числе когда событий
// нет вовсе. Поток типа `SubscriptionEvent` этого выразить не может: пришлось бы
// либо возить служебные поля в каждом событии, либо вынести их в метаданные
// вызова — то есть в место, где у них нет ни типа, ни разбора, ни `buf breaking`.
//
// Ветвление, а не два необязательных поля: сообщение, у которого пусты обе
// ветви, в этой форме просто негде построить, и подписчику не приходится решать,
// что значит «оба пусты» или «оба заполнены».
type SubscriptionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*SubscriptionMessage_Opened
	//	*SubscriptionMessage_Event
	Message       isSubscriptionMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionMessage) Reset() {
	*x = SubscriptionMessage{}
	mi := &file_corelib_subscription_subscription_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionMessage) ProtoMessage() {}

func (x *SubscriptionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_subscription_subscription_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionMessage.ProtoReflect.Descriptor instead.
func (*SubscriptionMessage) Descriptor() ([]byte, []int) {
	return file_corelib_subscription_subscription_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionMessage) GetMessage() isSubscriptionMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SubscriptionMessage) GetOpened() *SubscriptionOpened {
	if x != nil {
		if x, ok := x.Message.(*SubscriptionMessage_Opened); ok {
			return x.Opened
		}
	}
	return nil
}

func (x *SubscriptionMessage) GetEvent() *SubscriptionEvent {
	if x != nil {
		if x, ok := x.Message.(*SubscriptionMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isSubscriptionMessage_Message interface {
	isSubscriptionMessage_Message()
}

type SubscriptionMessage_Opened struct {
	// opened — служебное сообщение открытия. Приходит первым и ровно один раз за
	// поток.
	Opened *SubscriptionOpened `protobuf:"bytes,1,opt,name=opened,proto3,oneof"`
}

type SubscriptionMessage_Event struct {
	// event — событие. Приходит только после `opened`.
	Event *SubscriptionEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*SubscriptionMessage_Opened) isSubscriptionMessage_Message() {}

func (*SubscriptionMessage_Event) isSubscriptionMessage_Message() {}

var File_corelib_subscription_subscription_service_proto protoreflect.FileDescriptor

const file_corelib_subscription_subscription_service_proto_rawDesc = "" +
	"\n" +
	"/corelib/subscription/subscription_service.proto\x12\x14corelib.subscription\x1a'corelib/subscription/subscription.proto\x1a$corelib/authz/v1/authz_options.proto\"\xa5\x01\n" +
	"\x13SubscriptionMessage\x12B\n" +
	"\x06opened\x18\x01 \x01(\v2(.corelib.subscription.SubscriptionOpenedH\x00R\x06opened\x12?\n" +
	"\x05event\x18\x02 \x01(\v2'.corelib.subscription.SubscriptionEventH\x00R\x05eventB\t\n" +
	"\amessage2\xb1\x01\n" +
	"\x1bInternalSubscriptionService\x12\x91\x01\n" +
	"\tSubscribe\x12).corelib.subscription.SubscriptionRequest\x1a).corelib.subscription.SubscriptionMessage\",\x8a\xb5\x18\x1fplatform.subscription.subscribe\xa2\xb5\x18\x011\xb0\xb5\x18\x010\x01BIZGgithub.com/PRO-Robotech/corelib/api/corelib/subscription;subscriptionv1b\x06proto3"

var (
	file_corelib_subscription_subscription_service_proto_rawDescOnce sync.Once
	file_corelib_subscription_subscription_service_proto_rawDescData []byte
)

func file_corelib_subscription_subscription_service_proto_rawDescGZIP() []byte {
	file_corelib_subscription_subscription_service_proto_rawDescOnce.Do(func() {
		file_corelib_subscription_subscription_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corelib_subscription_subscription_service_proto_rawDesc), len(file_corelib_subscription_subscription_service_proto_rawDesc)))
	})
	return file_corelib_subscription_subscription_service_proto_rawDescData
}

var file_corelib_subscription_subscription_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_corelib_subscription_subscription_service_proto_goTypes = []any{
	(*SubscriptionMessage)(nil), // 0: corelib.subscription.SubscriptionMessage
	(*SubscriptionOpened)(nil),  // 1: corelib.subscription.SubscriptionOpened
	(*SubscriptionEvent)(nil),   // 2: corelib.subscription.SubscriptionEvent
	(*SubscriptionRequest)(nil), // 3: corelib.subscription.SubscriptionRequest
}
var file_corelib_subscription_subscription_service_proto_depIdxs = []int32{
	1, // 0: corelib.subscription.SubscriptionMessage.opened:type_name -> corelib.subscription.SubscriptionOpened
	2, // 1: corelib.subscription.SubscriptionMessage.event:type_name -> corelib.subscription.SubscriptionEvent
	3, // 2: corelib.subscription.InternalSubscriptionService.Subscribe:input_type -> corelib.subscription.SubscriptionRequest
	0, // 3: corelib.subscription.InternalSubscriptionService.Subscribe:output_type -> corelib.subscription.SubscriptionMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_corelib_subscription_subscription_service_proto_init() }
func file_corelib_subscription_subscription_service_proto_init() {
	if File_corelib_subscription_subscription_service_proto != nil {
		return
	}
	file_corelib_subscription_subscription_proto_init()
	file_corelib_subscription_subscription_service_proto_msgTypes[0].OneofWrappers = []any{
		(*SubscriptionMessage_Opened)(nil),
		(*SubscriptionMessage_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corelib_subscription_subscription_service_proto_rawDesc), len(file_corelib_subscription_subscription_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_corelib_subscription_subscription_service_proto_goTypes,
		DependencyIndexes: file_corelib_subscription_subscription_service_proto_depIdxs,
		MessageInfos:      file_corelib_subscription_subscription_service_proto_msgTypes,
	}.Build()
	File_corelib_subscription_subscription_service_proto = out.File
	file_corelib_subscription_subscription_service_proto_goTypes = nil
	file_corelib_subscription_subscription_service_proto_depIdxs = nil
}
