#!/usr/bin/env bash
# Generate / update obsidian/kacho/freeze-gate-status.md from the JSON report
# produced by run-all.sh.
#
# Usage:
#   ./scripts/freeze-gate/update-vault.sh <report.json> [vault-md-path]
#
# Default vault-md-path: <workspace>/obsidian/kacho/freeze-gate-status.md
#
# Exit 0 = vault updated, 1 = invalid args / missing report, 2 = jq absent.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WS="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ "$#" -lt 1 ]; then
    echo "usage: $0 <report.json> [vault-md-path]" >&2
    exit 1
fi

report="$1"
vault="${2:-$WS/obsidian/kacho/freeze-gate-status.md}"

if [ ! -f "$report" ]; then
    echo "report not found: $report" >&2
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "jq is required" >&2
    exit 2
fi

generated_at=$(jq -r '.generated_at' "$report")
pass=$(jq -r '.totals.pass' "$report")
fail=$(jq -r '.totals.fail' "$report")
skip=$(jq -r '.totals.skip' "$report")
crash=$(jq -r '.totals.crash' "$report")
total=$(jq -r '.totals.total' "$report")

ready="NO"
if [ "$fail" = "0" ] && [ "$crash" = "0" ] && [ "$pass" = "$total" ]; then
    ready="YES"
fi

mkdir -p "$(dirname "$vault")"

{
    echo "---"
    echo "title: \"Freeze gate status\""
    echo "generated_at: $generated_at"
    echo "freeze_ready: $ready"
    echo "---"
    echo
    echo "# Freeze gate status"
    echo
    echo "Auto-generated by \`scripts/freeze-gate/run-all.sh\` (KAC-178)."
    echo
    echo "- **Generated**: $generated_at"
    echo "- **Totals**: PASS=$pass FAIL=$fail SKIP=$skip CRASH=$crash (of $total)"
    echo "- **Freeze-ready**: $ready"
    echo
    echo "## Per-check status"
    echo
    echo "| Check | Status | Detail |"
    echo "|---|---|---|"
    jq -r '.checks[] | "| \(.name) | \(.status) | \(.detail) |"' "$report"
    echo
    echo "## Legend"
    echo
    echo "- **PASS** — gate green, no action needed."
    echo "- **FAIL** — freeze blocker; see check output and open a finding-issue."
    echo "- **SKIP** — preconditions missing (sibling repo not cloned, gh / kubectl unavailable)."
    echo "- **CRASH** — script error; infra/tooling issue, not a product gap."
    echo
    echo "Source spec: \`docs/specs/sub-phase-W3.4-freeze-checklist-acceptance.md\`."
} > "$vault"

echo "vault dashboard updated: $vault"
